version: '3.9'

services:
  db:
    image: gfabrissouza/docker-db
    command: mysqld --default_authentication_plugin=caching_sha2_password
    restart: always
    environment:
      TZ: America/Sao_Paulo
      MYSQL_ROOT_PASSWORD: docker
      MYSQL_USER: docker
      MYSQL_PASSWORD: docker
      MYSQL_DATABASE: db
      MYSQL_ROOT_HOST: '%'
      MYSQL_TCP_PORT: 3308
    ports:
      - 3308:3308
    expose:
      - 3308
    networks:
      - fabris-network

  docker-from-zero-to-mastery-dotnet-8:
    image: gfabrissouza/docker
    restart: always
    environment:
      TZ: America/Sao_Paulo
      MySQLConnection__MySQLConnectionString: "Server=db;Port=3308;DataBase=db;Uid=docker;Pwd=docker"
    ports:
      - 4430:8080
      - 44300:8081
    depends_on:
      - db
    networks:
      - fabris-network
networks:
  erudio-network:
    driver: bridge
